### ISSUE TITLE
"Unexpected identifier" when installing

### ISSUE THREAD

**Issue by jagthedrummer** [grimbonious/ember-cli-amplify#1]
When I try to install I get this:

```
$ ember install ember-cli-amplify
npm: Installed ember-cli-amplify
Unexpected identifier


Stack Trace and Error Report: /var/folders/hb/jkd1b3q16nl2xk1qx58mgl3m0000gn/T/error.dump.d5b4e2f50598a607b3739bdd652f45e9.log
```

And the contents of that log:

```
$ cat /var/folders/hb/jkd1b3q16nl2xk1qx58mgl3m0000gn/T/error.dump.d5b4e2f50598a607b3739bdd652f45e9.log
=================================================================================

ENV Summary:

  TIME: Thu Aug 09 2018 23:18:17 GMT-0500 (CDT)
  TITLE: ember
  ARGV:
  - /Users/jgreen/.nvm/versions/node/v6.10.3/bin/node
  - /Users/jgreen/.nvm/versions/node/v6.10.3/bin/ember
  - install
  - ember-cli-amplify
  EXEC_PATH: /Users/jgreen/.nvm/versions/node/v6.10.3/bin/node
  TMPDIR: /var/folders/hb/jkd1b3q16nl2xk1qx58mgl3m0000gn/T
  SHELL: /usr/local/bin/bash
  PATH:
  - /Users/jgreen/.nvm/versions/node/v6.10.3/bin
  - /Users/jgreen/Desktop/go_projects/bin
  - /usr/local/heroku/bin
  - /usr/local/bin
  - /usr/opt/local/sbin
  - /opt/local/bin
  - /opt/local/sbin
  - /Users/jgreen/.rvm/gems/ruby-2.3.1/bin
  - /Users/jgreen/.rvm/gems/ruby-2.3.1@global/bin
  - /Users/jgreen/.rvm/rubies/ruby-2.3.1/bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /Library/TeX/texbin
  - /opt/X11/bin
  - /Users/jgreen/.rvm/bin
  - /opt/local/lib/postgresql91/bin
  - /usr/local/mysql/bin
  - /Library/TeX/texbin
  - /Users/jgreen/Development/android-sdk-macosx/platform-tools
  - /Users/jgreen/Development/android-sdk-macosx/tools
  - /Users/jgreen/projects/maven/apache-maven-3.3.9/bin
  PLATFORM: darwin x64
  FREEMEM: 2122973184
  TOTALMEM: 17179869184
  UPTIME: 715474
  LOADAVG: 2.71484375,2.38134765625,2.29345703125
  CPUS:
  - Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz - 2700
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.10.1-DEV
  - http_parser: 2.7.0
  - icu: 58.2
  - modules: 48
  - node: 6.10.3
  - openssl: 1.0.2k
  - uv: 1.9.1
  - v8: 5.1.281.101
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Unexpected identifier
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Unexpected identifier
  - name: SyntaxError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: /Users/jgreen/projects/remarq-notes-ember/node_modules/ember-cli-amplify/blueprints/ember-cli-amplify/index.js:136
  async afterInstall(options) {
        ^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Function.Blueprint.load (/Users/jgreen/projects/remarq-notes-ember/node_modules/ember-cli/lib/models/blueprint.js:1284:31)
    at Function.Blueprint.lookup (/Users/jgreen/projects/remarq-notes-ember/node_modules/ember-cli/lib/models/blueprint.js:1261:24)
    at GenerateTask.lookupBlueprint (/Users/jgreen/projects/remarq-notes-ember/node_modules/ember-cli/lib/tasks/generate-from-blueprint.js:92:22)
    at GenerateTask.run (/Users/jgreen/projects/remarq-notes-ember/node_modules/ember-cli/lib/tasks/generate-from-blueprint.js:20:30)
    at promise.then (/Users/jgreen/projects/remarq-notes-ember/node_modules/ember-cli/lib/tasks/addon-install.js:63:26)
    at tryCatcher (/Users/jgreen/projects/remarq-notes-ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:323:19)
    at invokeCallback (/Users/jgreen/projects/remarq-notes-ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:495:31)
    at /Users/jgreen/projects/remarq-notes-ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:559:14
    at flush (/Users/jgreen/projects/remarq-notes-ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:2402:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)


=================================================================================
```

**Comment by jagthedrummer** [comment]
After updating my local node version I was able to install successfully.
